# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_income_client_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 350)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.client_label = QtWidgets.QLabel(Form)
        self.client_label.setObjectName("client_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.client_label)
        self.client_cb = QtWidgets.QComboBox(Form)
        self.client_cb.setObjectName("client_cb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.client_cb)
        self.add_btn = QtWidgets.QPushButton(Form)
        self.add_btn.setObjectName("add_btn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.add_btn)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lesson_type_cb = QtWidgets.QComboBox(Form)
        self.lesson_type_cb.setObjectName("lesson_type_cb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lesson_type_cb)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.start_lesson_time_le = QtWidgets.QLineEdit(Form)
        self.start_lesson_time_le.setObjectName("start_lesson_time_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.start_lesson_time_le)
        self.end_lesson_time_le = QtWidgets.QLineEdit(Form)
        self.end_lesson_time_le.setObjectName("end_lesson_time_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.end_lesson_time_le)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить клиента"))
        self.client_label.setText(_translate("Form", "Клиент"))
        self.add_btn.setText(_translate("Form", "Добавить"))
        self.label_2.setText(_translate("Form", "Время начала занятия"))
        self.label_3.setText(_translate("Form", "Тип занятия"))
        self.label.setText(_translate("Form", "Время конца занятия"))
        self.start_lesson_time_le.setInputMask(_translate("Form", "00:00"))
        self.end_lesson_time_le.setInputMask(_translate("Form", "00:00"))
        self.end_lesson_time_le.setText(_translate("Form", ":"))
