# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_client_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 455)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.client_label = QtWidgets.QLabel(Form)
        self.client_label.setObjectName("client_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.client_label)
        self.client_cb = QtWidgets.QComboBox(Form)
        self.client_cb.setObjectName("client_cb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.client_cb)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.name_edit = QtWidgets.QLineEdit(Form)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_edit)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.phone_edit = QtWidgets.QLineEdit(Form)
        self.phone_edit.setObjectName("phone_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.phone_edit)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.reg_date_de = QtWidgets.QDateEdit(Form)
        self.reg_date_de.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.reg_date_de.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.reg_date_de.setCalendarPopup(False)
        self.reg_date_de.setDate(QtCore.QDate(2020, 11, 20))
        self.reg_date_de.setObjectName("reg_date_de")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.reg_date_de)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lessons_amount_sb = QtWidgets.QSpinBox(Form)
        self.lessons_amount_sb.setMaximum(10000)
        self.lessons_amount_sb.setObjectName("lessons_amount_sb")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lessons_amount_sb)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.duration_sb = QtWidgets.QSpinBox(Form)
        self.duration_sb.setMaximum(10000)
        self.duration_sb.setSingleStep(1)
        self.duration_sb.setProperty("value", 31)
        self.duration_sb.setObjectName("duration_sb")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.duration_sb)
        self.save_changes_btn = QtWidgets.QPushButton(Form)
        self.save_changes_btn.setObjectName("save_changes_btn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.save_changes_btn)
        self.birth_date_de = QtWidgets.QDateEdit(Form)
        self.birth_date_de.setObjectName("birth_date_de")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.birth_date_de)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменение клиентской базы"))
        self.client_label.setText(_translate("Form", "Клиент"))
        self.name_label.setText(_translate("Form", "ФИО"))
        self.label_3.setText(_translate("Form", "Телефон"))
        self.label_7.setText(_translate("Form", "Дата регистрации"))
        self.label_4.setText(_translate("Form", "Дата рождения"))
        self.label_5.setText(_translate("Form", "Количество занятий"))
        self.label_6.setText(_translate("Form", "Длительность абонемента"))
        self.save_changes_btn.setText(_translate("Form", "Внести изменения"))
