# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_client_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 455)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.client_label = QtWidgets.QLabel(Form)
        self.client_label.setObjectName("client_label")
        self.gridLayout_2.addWidget(self.client_label, 0, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(Form)
        self.name_label.setObjectName("name_label")
        self.gridLayout_2.addWidget(self.name_label, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.birth_date_le = QtWidgets.QLineEdit(Form)
        self.birth_date_le.setObjectName("birth_date_le")
        self.gridLayout_2.addWidget(self.birth_date_le, 4, 1, 1, 1)
        self.save_changes_btn = QtWidgets.QPushButton(Form)
        self.save_changes_btn.setObjectName("save_changes_btn")
        self.gridLayout_2.addWidget(self.save_changes_btn, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.reg_date_le = QtWidgets.QLineEdit(Form)
        self.reg_date_le.setObjectName("reg_date_le")
        self.gridLayout_2.addWidget(self.reg_date_le, 3, 1, 1, 1)
        self.select_born_date_btn = QtWidgets.QPushButton(Form)
        self.select_born_date_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.select_born_date_btn.setObjectName("select_born_date_btn")
        self.gridLayout_2.addWidget(self.select_born_date_btn, 4, 2, 1, 1)
        self.select_reg_date_btn = QtWidgets.QPushButton(Form)
        self.select_reg_date_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.select_reg_date_btn.setObjectName("select_reg_date_btn")
        self.gridLayout_2.addWidget(self.select_reg_date_btn, 3, 2, 1, 1)
        self.phone_edit = QtWidgets.QLineEdit(Form)
        self.phone_edit.setObjectName("phone_edit")
        self.gridLayout_2.addWidget(self.phone_edit, 2, 1, 1, 2)
        self.name_edit = QtWidgets.QLineEdit(Form)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout_2.addWidget(self.name_edit, 1, 1, 1, 2)
        self.client_cb = QtWidgets.QComboBox(Form)
        self.client_cb.setObjectName("client_cb")
        self.gridLayout_2.addWidget(self.client_cb, 0, 1, 1, 2)
        self.lessons_amount_sb = QtWidgets.QSpinBox(Form)
        self.lessons_amount_sb.setMaximum(10000)
        self.lessons_amount_sb.setObjectName("lessons_amount_sb")
        self.gridLayout_2.addWidget(self.lessons_amount_sb, 5, 1, 1, 2)
        self.duration_sb = QtWidgets.QSpinBox(Form)
        self.duration_sb.setMaximum(10000)
        self.duration_sb.setSingleStep(1)
        self.duration_sb.setProperty("value", 31)
        self.duration_sb.setObjectName("duration_sb")
        self.gridLayout_2.addWidget(self.duration_sb, 6, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменение клиентской базы"))
        self.label_7.setText(_translate("Form", "Дата регистрации"))
        self.client_label.setText(_translate("Form", "Клиент"))
        self.name_label.setText(_translate("Form", "ФИО"))
        self.label_6.setText(_translate("Form", "Длительность абонемента"))
        self.label_4.setText(_translate("Form", "Дата рождения"))
        self.label_5.setText(_translate("Form", "Количество занятий"))
        self.birth_date_le.setInputMask(_translate("Form", "0000.00.00"))
        self.save_changes_btn.setText(_translate("Form", "Внести изменения"))
        self.label_3.setText(_translate("Form", "Телефон"))
        self.reg_date_le.setInputMask(_translate("Form", "0000.00.00"))
        self.select_born_date_btn.setText(_translate("Form", "📅"))
        self.select_reg_date_btn.setText(_translate("Form", "📅"))
