# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_info_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(588, 454)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.exit_btn = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setObjectName("exit_btn")
        self.gridLayout.addWidget(self.exit_btn, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.client_report = QtWidgets.QWidget()
        self.client_report.setObjectName("client_report")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.client_report)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.client_report)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.date_filter_de = QtWidgets.QDateEdit(self.client_report)
        self.date_filter_de.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 1), QtCore.QTime(0, 0, 0)))
        self.date_filter_de.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 12, 31), QtCore.QTime(0, 0, 0)))
        self.date_filter_de.setMinimumDate(QtCore.QDate(2019, 12, 31))
        self.date_filter_de.setObjectName("date_filter_de")
        self.gridLayout_2.addWidget(self.date_filter_de, 1, 1, 1, 1)
        self.client_info_table = QtWidgets.QTableWidget(self.client_report)
        self.client_info_table.setObjectName("client_info_table")
        self.client_info_table.setColumnCount(5)
        self.client_info_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.client_info_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_info_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_info_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_info_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_info_table.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.client_info_table, 2, 0, 1, 2)
        self.tabWidget.addTab(self.client_report, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.client_name_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.client_name_label.setFont(font)
        self.client_name_label.setText("")
        self.client_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.client_name_label.setObjectName("client_name_label")
        self.gridLayout.addWidget(self.client_name_label, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Информация о клиенте"))
        self.exit_btn.setText(_translate("Form", "Закрыть"))
        self.label_2.setText(_translate("Form", "Показывать отчет с даты:                                                   "))
        item = self.client_info_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Операция"))
        item = self.client_info_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Дата"))
        item = self.client_info_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Время"))
        item = self.client_info_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Тип занятия/сумма"))
        item = self.client_info_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Кол-во занятий"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.client_report), _translate("Form", "Отчет по клиенту"))
