# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lesson_timer_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        self.time = QtWidgets.QLabel(Form)
        self.time.setGeometry(QtCore.QRect(0, 75, 800, 400))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(108)
        self.time.setFont(font)
        self.time.setText("")
        self.time.setTextFormat(QtCore.Qt.AutoText)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.lesson_types = QtWidgets.QComboBox(Form)
        self.lesson_types.setGeometry(QtCore.QRect(250, 10, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lesson_types.setFont(font)
        self.lesson_types.setCurrentText("")
        self.lesson_types.setObjectName("lesson_types")
        self.stop_btn = QtWidgets.QPushButton(Form)
        self.stop_btn.setGeometry(QtCore.QRect(300, 475, 200, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        self.stop_btn.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        self.stop_btn.setFont(font)
        self.stop_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stop_btn.setAutoFillBackground(False)
        self.stop_btn.setObjectName("stop_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Время занятия"))
        self.stop_btn.setText(_translate("Form", "Старт"))
